name: MS Var replacement

on:
  push:
    branches:
      - main

jobs:
  VarReplacement:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout Code

      - uses: microsoft/variable-substitution@v1
        name: Toggle config.yaml
        with:
          files: 'config/config.yaml'
        env:
          run_settings.use_sample: true

      - name: print config after replacement
        run: |
          cat config.yaml
